In [6]:
import numpy as np

In [7]:
a = np.array([1, 2, 3])
b = a # b is a reference to a
b[0] = 5
print(a)
print(b)

[5 2 3]
[5 2 3]


In [8]:
a = np.array([1, 2, 3])
b = a.copy() # b is a copy of a
b[0] = 5
print(a)
print(b)

[1 2 3]
[5 2 3]
