In [28]:
import numpy as np

In [29]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [31]:
np.full((2, 3), 7)

array([[7, 7, 7],
       [7, 7, 7]])

In [32]:
np.eye(3) # identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.linspace(0, 10, 5) # start, end, number of points

array([ 0. ,  2.5,  5. ,  7.5, 10. ])