In [17]:
import numpy as np

In [18]:
np.random.random((3,2)) # 0-1

array([[0.95824459, 0.87552569],
       [0.78535777, 0.13430317],
       [0.12233882, 0.46287425]])

In [19]:
np.random.randn(3,2) # normal/gaussian distribution

array([[-0.41943944, -0.22534877],
       [ 0.14332616,  0.20420984],
       [ 0.38938556,  1.59463089]])

In [20]:
a = np.random.randn(1000)
print(a.mean(), a.var())

0.06316259034242026 1.0063477649028925


In [21]:
np.random.randint(3,10, size=(3,3)) # 3-9

array([[8, 7, 5],
       [5, 4, 8],
       [9, 9, 9]])

In [22]:
np.random.choice(5, size=(10)) # 0-9

array([1, 3, 0, 1, 0, 3, 3, 3, 4, 1])

In [23]:
np.random.choice([-8, -7, -6], size=(10))

array([-7, -8, -6, -8, -7, -6, -7, -8, -8, -7])