In [1]:
import numpy as np

In [2]:
l = [1, 2, 3]
a = np.array([1, 2, 3])
print(l)
print(a)

[1, 2, 3]
[1 2 3]


In [3]:
l.append(4)
# a.append(4) # error

In [4]:
l = l + [5]
a = a + np.array([4]) # same as a = a + np.array([4, 4, 4])
print(l)
print(a)

[1, 2, 3, 4, 5]
[5 6 7]


In [5]:
l = l * 2
a = a * 2
print(l)
print(a)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[10 12 14]


In [6]:
a = np.sqrt(a)
print(a)
a = np.log(a)
print(a)

[3.16227766 3.46410162 3.74165739]
[1.15129255 1.24245332 1.31952866]
