In [50]:
import numpy as np

In [51]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.shape

(2, 3)

In [52]:
a[0,0]

1

In [53]:
a[:,0]

array([1, 4])

In [54]:
a[0,:]

array([1, 2, 3])

In [55]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [56]:
b = np.array([[1, 2], [3, 4]])
np.linalg.inv(b)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [57]:
np.linalg.det(b)

-2.0000000000000004

In [58]:
np.diag(b)

array([1, 4])