In [75]:
import numpy as np

In [76]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [77]:
a[0,1]

2

In [78]:
a[0,1:3] # start at 0, go to 1, but not including 3

array([2, 3])

In [79]:
a[:,1] # all rows, column 1

array([2, 6])

In [80]:
a[-1,-1] # last row, last column

8

In [81]:
a = np.array([[1, 2], [3, 4], [5, 6]])

In [82]:
bool_idx = (a > 2) # find the elements of a that are bigger than 2
print(bool_idx)
print(a[bool_idx])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


In [83]:
a[a > 2]

array([3, 4, 5, 6])

In [84]:
np.where(a > 2, a, -1)

array([[-1, -1],
       [ 3,  4],
       [ 5,  6]])

In [85]:
a = np.array([10, 19, 30, 41, 50, 61])
b = np.array([1, 3, 5]) # fancy indexing
a[b]

array([19, 41, 61])