In [19]:
import numpy as np

In [20]:
a = np.arange(1, 7)
a

array([1, 2, 3, 4, 5, 6])

In [21]:
a.reshape((2, 3))

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
a.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
a[np.newaxis, :]

array([[1, 2, 3, 4, 5, 6]])

In [24]:
a[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])