In [33]:
import numpy as np

In [34]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

In [35]:
np.concatenate((a, b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [36]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6])

In [38]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [39]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [40]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
np.vstack((a, b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])