In [30]:
import numpy as np

In [31]:
a = np.array([[7,8,9,10,11,12,13], [14,15,16,17,18,19,20]])

In [32]:
a.sum()

189

In [33]:
a.sum(axis=0) # sum of each column

array([21, 23, 25, 27, 29, 31, 33])

In [34]:
a.sum(axis=1) # sum of each row

array([ 70, 119])

In [35]:
a.mean()

13.5

In [36]:
a.mean(axis=0)

array([10.5, 11.5, 12.5, 13.5, 14.5, 15.5, 16.5])

In [37]:
a.mean(axis=1)

array([10., 17.])

In [38]:
a.var() # variance

16.25

In [39]:
a.std() # standard deviation

4.031128874149275

In [40]:
a.min()

7

In [41]:
a.max()

20